#!/bin/sh

xsetroot -cursor_name left_ptr
sxhkd &
panel &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio        0.5

bspc config normal_border_color  "#252525"
bspc config focused_border_color "#525252"

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier     mod1
bspc config click_to_focus       button1

bspc rule -a Firefox desktop='^2' border=off
bspc rule -a mpv state=floating
bspc rule -a Zathura state=tiled
